os: linux
dist: xenial

language: android

cache:
  directories:
    - $HOME/.gradle

before_cache:
  # Remove daemon logs, bin databases, and lockfiles
  - rm -rf $HOME/.gradle/daemon/
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

jdk: oraclejdk8

env:
  - TEST_SUITE="codenarc integTest"
  # analyze each tool independently
  - TEST_SUITE="perfTest --tests *.ConfigurationPerfTest.*"
  - TEST_SUITE="perfTest --tests *.PmdPerfTest.*"
  - TEST_SUITE="perfTest --tests *.CheckstylePerfTest.*"
  - TEST_SUITE="perfTest --tests *.CpdPerfTest.*"
  # split spotbugs tests as those are slower and timeout
  - TEST_SUITE="perfTest --tests *.SpotbugsPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.AndroidScenario"
  - TEST_SUITE="perfTest --tests *.SpotbugsPerfTest.* -PperfTestCategory=com.monits.gradle.sca.performance.categories.JavaScenario"

android:
  components:
    - tools
    - build-tools-28.0.3
    - build-tools-29.0.2
    - android-23
    - android-25

branches:
  only:
    - development
    - staging
    - /^support-.*$/

script:
  - ./gradlew assemble $TEST_SUITE
  - ./gradlew --stop
