/*
 * Copyright 2010-2016 Monits S.A.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.monits.gradle.sca.config

import com.monits.gradle.sca.ClasspathAware
import com.monits.gradle.sca.StaticCodeAnalysisExtension
import com.monits.gradle.sca.ToolVersions
import com.monits.gradle.sca.task.DownloadTask
import org.gradle.api.Project
import org.gradle.api.file.FileTree
import org.gradle.api.plugins.quality.FindBugs
import org.gradle.api.tasks.compile.JavaCompile

/**
 * A configurator for Findbugs tasks
*/
class FindbugsConfigurator implements AnalysisConfigurator, ClasspathAware {
    private static final String FINDBUGS = 'findbugs'

    @Override
    void applyConfig(Project project, StaticCodeAnalysisExtension extension) {
        // TODO : Not currently working on java projects
        applyAndroidConfig(project, extension)
    }

    @SuppressWarnings('UnnecessaryGetter')
    @Override
    void applyAndroidConfig(Project project, StaticCodeAnalysisExtension extension) {
        // prevent applying it twice
        if (project.tasks.findByName(FINDBUGS)) {
            return
        }

        //FIXME: This is here so that projects that use Findbugs can compile... but it ignores DSL completely
        project.repositories {
            maven {
                url 'http://nexus.monits.com/content/repositories/oss-snapshots'
            }
        }
        project.dependencies {
            provided 'com.google.code.findbugs:annotations:' + ToolVersions.findbugsVersion
        }

        project.plugins.apply FINDBUGS

        project.dependencies {
            findbugs project.configurations.findbugsPlugins.dependencies

            // To keep everything tidy, we set these apart
            findbugsPlugins('com.monits:findbugs-plugin:' + ToolVersions.monitsFindbugsVersion) {
                transitive = false
            }
            findbugsPlugins 'com.mebigfatguy.fb-contrib:fb-contrib:' + ToolVersions.fbContribVersion
        }

        boolean remoteLocation = isRemoteLocation(extension.getFindbugsExclude())
        File filterSource
        String downloadTaskName = 'downloadFindbugsExcludeFilter'
        if (remoteLocation) {
            filterSource = makeDownloadFileTask(project, extension.getFindbugsExclude(),
                    'excludeFilter.xml', downloadTaskName, FINDBUGS)
        } else {
            filterSource = new File(extension.getFindbugsExclude())
        }

        project.findbugs {
            toolVersion = ToolVersions.findbugsVersion
            effort = 'max'
            ignoreFailures = extension.getIgnoreErrors()
            excludeFilter = filterSource
        }

        project.task(FINDBUGS, type:FindBugs) {
            dependsOn project.tasks.withType(JavaCompile)
            if (remoteLocation) {
                dependsOn project.tasks.findByName(downloadTaskName)
            }

            classes = getProjectClassTree(project)

            source 'src'
            include '**/*.java'
            exclude '**/gen/**'

            reports {
                xml {
                    destination "$project.buildDir/reports/findbugs/findbugs.xml"
                    xml.withMessages true
                }
            }

            pluginClasspath = project.configurations.findbugsPlugins
        }

        /*
         * For best results, Findbugs needs ALL classes, including Android's SDK,
         * but the task is created dynamically, so we need to set it afterEvaluate
         */
        configAndroidClasspath(project.tasks[FINDBUGS], project)

        project.tasks.check.dependsOn project.tasks[FINDBUGS]
    }

    private static boolean isRemoteLocation(String path) {
        path.startsWith('http://') || path.startsWith('https://')
    }

    private File makeDownloadFileTask(Project project, String remotePath, String destination,
                                      String taskName, String plugin) {
        GString destPath = "${project.rootDir}/config/${plugin}/"
        File destFile = project.file(destPath + destination)

        project.task(taskName, type:DownloadTask) {
            directory = project.file(destPath)
            downloadedFile = destFile
            resourceUri = remotePath
        }

        destFile
    }

    /**
     * Retrieves a FileTree pointing to all interesting .class files for
     * static code analysis. This ignores for instance, Android's autogenerated classes
     *
     * @param proj The project whose class file tree to obtain.
     * @return FileTree pointing to all interesting .class files
     */
    private static FileTree getProjectClassTree(Project proj) {
        FileTree tree = proj.fileTree(dir:"${proj.buildDir}/intermediates/classes/")

        tree.with {
            exclude '**/R.class' //exclude generated R.java
            exclude '**/R$*.class' //exclude generated R.java inner classes
            exclude '**/Manifest.class' //exclude generated Manifest.java
            exclude '**/Manifest$*.class' //exclude generated Manifest.java inner classes
            exclude '**/BuildConfig.class' //exclude generated BuildConfig.java
            exclude '**/BuildConfig$*.class' //exclude generated BuildConfig.java inner classes
        }

        tree
    }
}
